### ISSUE TITLE
Problem with utils/negligible? function

### ISSUE THREAD

**Issue by gabrielsimoes** [deg/iron#1]
I'm not sure whether it is expected behavior or not, but if you pass `false` to `negligible?` function, it'll return true. However, I don't think `false` should be negligible, especially when used in `re-utils/>evt`. 

I may want to pass an argument to my event which can either be `true` or `false`, with a default value of `true`. In this case, `>evt` would always dispatch the event with a `true` value, even when provided with `false`.

Edit: It could be a good idea to always return true when the argument is a non-seq.

**Comment by deg** [comment]
Oops, thanks.  Definitely sounds like a bug; I'm not sure how I missed that case.
I'm in the middle of a crunch now on another project, but will take a look soon.

**Comment by deg** [comment]
Fixed in v0.4.0.  Thanks!
